### PR TITLE
Add modaliases to open-vm-tools-desktop

### PR DESCRIPTION
**Pull request by jibel**
Added Modaliases to open-vm-tools-desktop to auto-discover and
auto-install the driver on Ubuntu via ubuntu-drivers. The driver is then
installed at installation time and available on first boot for an
improved user experience (LP: #1819207)

### CODE REVIEW

**Comment by bzed** [comment]
@jibel sorry, but I don't apply Ubuntu specific patches. Please find a solution that works for Debian and *all* derivates. One is ucrrently being discussed in https://github.com/vmware/open-vm-tools/issues/214 and will be checked by vmware.

**Comment by cpaelzer** [comment]
HI @bzed I'm chiming in to clarify that this is not the same issue as [vmtools#214](https://github.com/vmware/open-vm-tools/issues/214).

214 is about ensuring the driver is fully loaded at the time it is needed.

This issue here opened by @jibel is about allowing applications like [ubuntu-drivers](https://launchpad.net/ubuntu/+source/ubuntu-drivers-common) to auto-detect (virtual) hardware and install the right packages/drivers for it.

AFAIK there is no such infrastructure in Debian yet (happy to learn that this is be different) and this is why I asked @jibel on the corresponding [Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1819207/comments/5) to code it up in a way that will not conflict with Debian - and I think he has achieved this.

If one day Debian uses the same/similar mechanism for auto-driver installation you could just drop the Vendor check and if not it would not hurt you as it should not degrade Debian in any way.

I'd appreciate if you'd reconsider the decision, but if "no Ubuntu specific patches" is a hard rule then even the explanation above won't help.

@jibel - I'm not a desktop guy at all, do you maybe know of other cases where modalias code was accepted into the Debian package - even though they do not benefit (yet)?

**Comment by jibel** [comment]
A similar package in Debian would be VirtualBox.

The implementation is slightly different. They generate substvars strings for virtualbox-guest-dkms and virtualbox-guest-x11 in dh_auto_install. It's special cased for Ubuntu (the name of the distro is determined with lsb_release)

ifeq ($(DIST_NAME),Ubuntu)
    echo "modaliases=vboxguest(pci:v000080EEd0000CAFEsv00000000sd00000000bc*sc*i*)" >> debian/$(gdkms).substvars
    echo "modaliases=vboxx11(pci:v000080EEd0000BEEFsv00000000sd00000000bc*sc*i*)" >> debian/$(uxname).substvars
endif

**Comment by bzed** [comment]
@jibel @cpaelzer okay, then I failed to understand what the idea behind the patch was - sorry :)

**Comment by bzed** [comment]
I'd like to wait with an upload a bit to see if there is a solution for that modprobe issue, or are you in a hurry?

**Comment by jibel** [comment]
Thanks for your review and merging this change.
Not really in a hurry, we're past feature freeze in Ubuntu and can maintain the delta until the package is synced into the distro.

**Pull request merged**
