### PR TITLE
ensure open-vm-tools starts after display-manager

### PR DESCRIPTION
**Pull request by mykmelez**
In order for open-vm-tools to resize the guest display resolution to the host resolution (when the VM is configured to do so), open-vm-tools apparently has to start after display-manager. However, currently, it can race that service. This change ensures that it waits for display-manager before starting.

The change comes from the conversation in https://communities.vmware.com/message/2816924 about working around this problem in an Ubuntu installation. But I expect that the fix is relevant for Debian itself (and other derivatives besides Ubuntu).

### CODE REVIEW

**Comment by bzed** [comment]
Hi,

while this might be a workaround for desktop users, this way to fix it would break basically all ways to provision a VM from withoin esx at boot time. vmtoolsd needs to start before the network comes up to be able to configure the network and other things using cloud-init.

Please open an issue at https://github.com/vmware/open-vm-tools

Thanks,

Bernd

**Comment by mykmelez** [comment]
Thanks for the explanation. It looks like it's already filed on open-vm-tools as https://github.com/vmware/open-vm-tools/issues/214, so I'll follow the issue there.

**Comment by bzed** [comment]
@mykmelez https://github.com/bzed/pkg-open-vm-tools/commit/dc4e1cefe69c78a70ce322ed6b520b7c0551fcb1

**Comment by mykmelez** [comment]
> @mykmelez [dc4e1ce](https://github.com/bzed/pkg-open-vm-tools/commit/dc4e1cefe69c78a70ce322ed6b520b7c0551fcb1)

Thanks, I've tested locally and confirmed that it resolves the problem!

**Pull request closed without merging**
